### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by PasteLord** [hallzy/youtube-playlist-search#11]
When going into Extensions on the google settings and pressing Load unpacked, it fails to load.

I have tried to delete the whole project on the google cloud and redo all the steps but even with different client IDs it still shows the same thing.
![image](https://user-images.githubusercontent.com/83995254/179681192-20c4784c-bf41-44a4-95a0-ca705f2f8b74.png)

Don't know if you remember me but long time no see, hows the extension coming long? Recently got a new pc which is why I needed to reinstall this lol.

**Comment by PasteLord** [comment]
Nvm I'm a dummy gotem 🤡. Idk what I was thinking 13 hours ago but I replaced the actual line called "client_id" with the my client id not the id after it.

**Comment by hallzy** [comment]
Glad you got it sorted out. Sorry I wasn’t able to respond sooner.
