### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ac4man** [hallzy/youtube-playlist-search#4]
When I click on the extension it makes me log in to my Google account, when I type something into either the "channel filter" or "search this playlist" nothing comes up. When I click on the extension again it prompts me to log in to my Google account again, and the cycle continues.

**Comment by hallzy** [comment]
You have to login to a google account to use it.

The extension uses the YouTube API provided by Google, and the extension need an auth token from google to perform API requests. The extension can only get the token if you give google permission to give that to the extension.

The token that the extension gets from google only gives the extension readonly access to the youtube api per the manifest file:

```
  "oauth2": {
    "scopes": [
      "https://www.googleapis.com/auth/youtube.readonly"
    ]
  },
```
