### ISSUE TITLE
"This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

### ISSUE THREAD

**Issue by bacevs** [hallzy/youtube-playlist-search#6]
My google account has 2 factor enabled. I'm presented with this error when trying to sign in through the extension.

"This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

I've tried creating an "app password" but it's not recognising the password.

**Comment by hallzy** [comment]
You shouldn't need an app password. I also use 2FA.

Do you have a screenshot of the page? Usually there is something you can click to ignore the warning

**Comment by bacevs** [comment]
> You shouldn't need an app password. I also use 2FA.
> 
> Do you have a screenshot of the page? Usually there is something you can click to ignore the warning

Screen shot link and attached below: 

![chrrr](https://user-images.githubusercontent.com/1433845/151106503-38182099-9da8-41dc-a66c-271c50a05540.jpg)

[Screenshot](https://i.imgur.com/kiMCe2d.jpg)

Browser: Google Chrome Version 97.0.4692.99 (Official Build) (64-bit

**Comment by hallzy** [comment]
Strange, I have never seen this. Not just for this, but for anything.

As per usual, this isn't something I can fix with my code, it looks to be a google security measure.

I came across this: https://devanswers.co/allow-less-secure-apps-access-gmail-account/

Maybe something there might help you?

It says that there is a setting to allow "Less Secure Apps"... but that setting isn't available if you have 2FA turned on, so it says to create an app specific password like you said you did... it says that if you can't login with it, to go here: https://accounts.google.com/DisplayUnlockCaptcha

And that is supposed to magically fix things ¯\\\_(ツ)_/¯

Let me know if that page works for you (https://devanswers.co/allow-less-secure-apps-access-gmail-account/).

By any chance, is this a personal account, or a work or school account? Looks like with Google Workspaces/ GSuite, administrators may block you out right from using "Less Secure Apps". So if you're not using a personal account, it is possible you may be sol.

**Comment by hallzy** [comment]
Closing as this hasn't gotten any updates in 2 weeks.
