### ISSUE TITLE
"Error: couldn't retrieve YouTube API Auth Token"

### ISSUE THREAD

**Issue by TheNonSmoker** [hallzy/youtube-playlist-search#7]
![Screenshot 2022-02-10 015319](https://user-images.githubusercontent.com/30073064/153283947-b7aa4992-35b1-47dc-b4ee-4c0762db9447.png)

Please provide a fix!

**Comment by TheNonSmoker** [comment]
Btw, [this](https://chrome.google.com/webstore/detail/playlist-search-for-youtu/jdolgjncmhmboklhmacpknglmiibbldg/related?hl=en) extension is also not working, saying "Invalid playlist."

**Comment by hallzy** [comment]
Apparently this extension is more popular than anticipated... Looks like I have reached the maximum 100 users cap for unverified apps, which is probably why you are seeing this error.

I'll have to think about what I am going to do here... I tried getting this verified a while back and it was an absolute nightmare so I gave up (google kept asking me to update things to conform to their rules which I already had done and it wasn't good enough somehow and there was no additional information and no human to talk to).

Given how terrible of an experience that was, I am not doing that. If someone else has more patience than I do maybe they can do it. I might just provide instructions for people to create their own API keys instead

**Comment by TheNonSmoker** [comment]
Ok, Also thanks for the effort, I can understand 👍

**Comment by hallzy** [comment]
@Soumyadeep98O I've updated the README with instructions on how to create an API key. Hopefully that is sufficient for you? Let me know if you have problems or something isn't clear with the instructions.

I really wish YouTube would just add this feature natively.

**Comment by TheNonSmoker** [comment]
Got my Client ID! But sorry to ask a stupid question, can you tell me where to put my Client ID? 😶?

**Comment by hallzy** [comment]
Yup, I think I added it into the installation instructions, but you open up the `manifest.json` file and paste your client id in place of the current client_id

ie, you change this line: `"client_id": "104618134280-roirvkp72379ll5d19ej7gl7128l5jk9.apps.googleusercontent.com",`

**Comment by TheNonSmoker** [comment]
Still same!
![Screenshot 2022-02-13 141316](https://user-images.githubusercontent.com/30073064/153745709-5328af98-f611-45da-a13d-a0df65aff065.png)

**Comment by hallzy** [comment]
Did you get prompted to login or allow access or anything?

It looks like you are using Microsoft Edge based on the icon on the devtools there, is that true?

I have never tried this extension in edge but I don't think it will work. I know that Edge is chrome based, but I think that google doesn't allow non Google Chrome Browsers to use their youtube api (All the more reason it would be nice for youtube to do this natively... not everyone uses or wants to use chrome)

Could you try this extension in Google Chrome and see if it works then?

Also I don't know if you reloaded the extension but that might make a difference too. Should be able to do that by clicking this button on the extension page (assuming edge looks the same)

![image](https://user-images.githubusercontent.com/5404143/153767870-f3945616-88c0-4537-8fd3-e907012ddf28.png)

**Comment by PasteLord** [comment]
Yo, I've done all the steps as said aswell as reinstalled the extension. It did give me a pop up to login but instead of showing  API error it should this:
![image](https://user-images.githubusercontent.com/83995254/156239477-a7eb3bd2-b004-414c-9344-c05b8c2856a4.png)
![image](https://user-images.githubusercontent.com/83995254/156244122-97195ca4-0047-40ce-8661-7354e0c29a5c.png)

**Comment by hallzy** [comment]
Looks like your app is in "testing", and I think you have to whitelist email addresses to use that. If you used the same google account to setup the google cloud as you are trying to use with the app it should be fine

In the "OAuth Consent Screen" there should be a publishing status. My guess is that yours says testing... Here you might be able to add email addresses, or set it to "In Production"

![image](https://user-images.githubusercontent.com/5404143/156246859-f44832f4-b4d7-43e0-8258-98f5a6360140.png)

See if something there might work.

**Comment by PasteLord** [comment]
I clicked to make it in production but it says I need to prepare for verification. I can fill out all the forms except this:
![image](https://user-images.githubusercontent.com/83995254/156497980-b6069295-227f-4ac5-aae3-07467e2cb462.png)
Not sure what domain I should add since I have no knowledge about this kind of stuff lol.

**Comment by hallzy** [comment]
> I have no knowledge about this kind of stuff lol.

Welcome to the club.... uggghhhh, nothing is easy with google lol.

Did you have to add an application homepage? Maybe just use whatever you did there.

This is what mine looks like. I made a page for this extension when I was trying to get it verified. You can try using the same URLs I used if you want, hopefully it doesn't require you to verify the domain.

![image](https://user-images.githubusercontent.com/5404143/156499285-7e483b2e-10c0-4427-8584-25e2f1bd2bad.png)

The alternative would probably be to leave it in testing mode and just add the email addresses that you want to have access to it, which I think is doable. It should look something like this in testing mode:

![image](https://user-images.githubusercontent.com/5404143/156499700-8263c220-6b25-4259-9ad0-69aba6eaaf9c.png)

Then you can hopefully add users where it says "Add Users".

Let me know if this works.... Clearly I am going to have to update the documentation, cause obviously it is incomplete.

**Comment by PasteLord** [comment]
Yo my friend, got exams so I wasnt able to see the message but aside from that, method 1 didn't work but method 2 works wonders! Mfs at google making things ultra difficult for everything smh, bout start using bing or yahoo search engine fr.
Coding is too big brain for me, reason why I'm going into electrical engg 🤡

**Comment by hallzy** [comment]
lol, well Electrical Engineering is too big brain for me.

Glad to hear it worked, I'll close this and I'll update the install instructions later with what we found here.

Good luck with your studies :)
