### ISSUE TITLE
Playlist sidebar issue?

### ISSUE THREAD

**Issue by SingularityRS** [hallzy/youtube-playlist-search#9]
I'm not sure if this is an issue with the extension, but thought I'd ask. I'm working with a playlist that has 4270 videos on it. I can search for my videos perfectly fine. However when I click on the video, it does not load with the playlist sidebar, it's just a standalone video. This issue seems to affect videos that are deep in my playlist. For example, trying the first few videos works fine and even the 200th video. If I search for video #2800, it doesn't load the playlist sidebar on the new tab.

Is this a YouTube limitation or perhaps an issue with the extension on very large playlists? Just wondering.

**Comment by hallzy** [comment]
This is not something that I have noticed, but my largest playlist is about 2000 videos, so maybe your playlist has hit some edge case I don't know about. I found a 3000 item playlist and it was able to show the sidebar after I selected the 2800th video, so it seems like it should work.

Would this playlist be one that you'd be willing to share either here or privately so I can have a look?

Also, the name of the 2800th video would be nice so I don't have to scroll to figure out what video that is.

If you could also provide the URL of the page that the extension takes you to that would be useful.

**Comment by SingularityRS** [comment]
It seems like it's inconsistent. Today I've been trying various times and it seems to be working OK. 

This is the playlist I am working with https://www.youtube.com/playlist?list=FL0xX6DbXdcjmQDRdiaGjKEg

The video I was testing out when having the issue reported in the OP is called "Coone - Magical (Official HQ Preview)". It's video #2849. This wasn't the only video doing it. It was a lot of them that were deeper into the playlist.

The URL once it opens in the new tab is https://www.youtube.com/watch?v=YdIRg18Zz4w&list=FL0xX6DbXdcjmQDRdiaGjKEg

Today, I've done various deep video searches on the extensions and the video does load with the sidebar on the new tab. I am not sure what's going on. 

One thing I have noticed is when the sidebar does load, it does not jump to the video currently playing. It'll be about 150-200 videos behind the one playing. So, for example, if I search for video #2849, the sidebar will load at around videos #2650-ish. You'd have to scroll down a bit to get to the video currently playing. Are you noticing this on your end as well?

**Comment by hallzy** [comment]
Weird. I'll have a look and get back to you. I haven't had it not show the sidebar on me yet, but I'll see.

Can you also send me the URL of a video when it doesn't open the sidebar? The URL should always have a `&list=` in it to tell youtube to show the list in the sidebar. If the `&list=` is in the URL and the sidebar doesn't show then I'm pretty sure that is a youtube bug. If the URL doesn't have the `&list=` when it doesn't have the sidebar then it is probably my fault somewhere.

I did notice that the sidebar loads a few hundred videos off. I don't think there is anything I can do about that, that seems to just be what youtube does. Seems like a big on youtube's part. Even If I click on say the 200th video of the playlist in youtube and not in the extension it does the same thing.

**Comment by SingularityRS** [comment]
It hasn't happened again yet. So far the videos I've searched for have loaded the sidebar, even the ones towards the end of my playlist. I'll have to keep checking to see if the issue reoccurs. If it's a bug, it's not a very consistent one from the looks of it.

**Comment by hallzy** [comment]
No updates here for a while so I'm going to close. If something comes up again we can reopen.
